Repository hirosystems/stacks.js, pull requests merged in 2018-05, with the labels that each got.

#461 Encrypt files with provided key & change encrypt content to take public key
  CHANGELOG.md
  dist/blockstack.js
  src/storage/index.js
  tests/unitTests/src/unitTestsStorage.js
Labels: enhancement

#429 Allow encryption of files with provided public key
  src/storage/index.js
Labels: enhancement

#460 Support for signature and validation in getFile/putFile
  CHANGELOG.md
  src/auth/authMessages.js
  src/encryption.js
  src/errors.js
  src/storage/index.js
  tests/unitTests/src/unitTestsEncryption.js
  tests/unitTests/src/unitTestsStorage.js
Labels: feature

#426 Refactor promise handling in the proof validation
  CHANGELOG.md
  src/profiles/profileProofs.js
  src/profiles/services/service.js
  tests/unitTests/src/unitTestsProofs.js
Labels: bug, technical-debt

#471 No need to specify parameter in InvalidDIDError
  dist/blockstack.js
  src/errors.js
  tests/unitTests/src/index.js
  tests/unitTests/src/unitTestsErrors.js
Labels: bug

#475 Remove uri-js so create-react-app will build
  package-lock.json
  package.json
  src/utils.js
Labels: bug
