Repository hirosystems/stacks.js, pull requests merged in 2018-04, with the labels that each got.

#391 Expose identity address and decentralized ID on user object
  src/auth/authApp.js
Labels: enhancement

#401 Upgrade to bitcoinjs@3.3.0
  dist/blockstack.js
  docs.json
  package-lock.json
  package.json
  src/operations/skeletons.js
Labels: enhancement

#416 Allows for non-lowercase usernames to be verifiable in Hacker News
  src/profiles/services/hackerNews.js
  tests/testData/profiles/bruno.proofs.json
  tests/unitTests/src/sampleData.js
  tests/unitTests/src/unitTestsProofs.js
Labels: bug

#410 Remove dependency on hasprop
  package.json
  src/index.js
  src/profiles/profileSchemas/personLegacy.js
  tests/testData/profiles/naval-legacy-convert.json
  tests/unitTests/src/sampleData.js
  tests/unitTests/src/unitTestsProfiles.js
Labels: technical-debt

#402 Enable Custom Gaia Hubs
  src/auth/authMessages.js
Labels: bug

#425 Add namespace transactions and name revoke
  CHANGELOG.md
  src/auth/authSession.js
  src/network.js
  src/operations/safety.js
  src/operations/skeletons.js
  src/operations/txbuild.js
  tests/authTests/src/index.js
  tests/operationsTests/src/operationsTests.js
  tests/unitTests/src/unitTestsOperations.js
Labels: feature

#411 Improved error handling in authentication
  src/auth/authApp.js
  src/errors.js
  tests/unitTests/src/unitTestsAuth.js
Labels: technical-debt

#452 [Storage] encrypt and decrypt strings
  src/storage/index.js
  tests/unitTests/src/unitTestsStorage.js
Labels: feature
